name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 5 * * *' # every 15 mins
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5ddc1e30c52071b66f71ac07
